### ISSUE TITLE
Scaling On Queue Size

### ISSUE THREAD

**Issue by barakAtSoluto** [kubernetes-sigs/prometheus-adapter#183] opened 2019-04-08 06:44 UTC
Hi,

I'm trying to use the adapter in order to scale a service based on Azure queue size. 
I've installed [promitor scraper](https://promitor.io/ ) on my cluster. This service is collecting metrics from Azure and exposes them to Prometheus to scrape. 

What i'm trying to do now is have the queue length (already in prometheus) exposed under `/apis/custom.metrics.k8s.io/v1beta1/namespaces/*/queue-length` but i can't find the correct configuration for this. 

Is it possible? If so - how?
Thank you.

**Comment by tomkerkhove** [comment] 2019-04-08 06:45
_Subscribing in case the issue is related to Promitor_

**Comment by s-urbaniak** [comment] 2019-04-08 14:56
@barakAtSoluto I don't know anything about promitor, but if these are azure metrics, they shoulnd't be bound to Kubernetes resources.

In that case you could expose them as external metrics which recently landed. Documentation on how to configure external metrics generally (not concretely for promitor) will be added soon.

**Comment by tomkerkhove** [comment] 2019-04-08 15:05
Promitor just provides a scraping endpoint for Prometheus - https://promitor.io.

I think @barakAtSoluto is asking how he can link his Prometheus metric to the adapter, is that correct?

**Comment by barakAtSoluto** [comment] 2019-04-08 15:15
@tomkerkhove is correct. Promitor is getting scraped by Prometheus. I have the TS as shown in the pic and i'm trying to access it from an HPA of a different service in a different NS. 

![image](https://user-images.githubusercontent.com/36621358/55735471-0de8d600-5a2a-11e9-8003-7d290cec5f7e.png)

**Comment by barakAtSoluto** [comment] 2019-04-08 15:16
@s-urbaniak I'd love to be an early adopter of the external metric. If you'd like I can test the docs before publish.

**Comment by s-urbaniak** [comment] 2021-03-01 09:26
we can close this out as external metrics are implemented.

**Closed by s-urbaniak** 2021-03-01 09:26 UTC
Labels: docs, lifecycle/rotten
